# Generated by Django 5.1.2 on 2024-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrifto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='encrypted_balance',
            field=models.BinaryField(default=b'gAAAAABnGSwGn4oJW8P9vLwT92WCAlrVwN4hCBQhw8i3f7IOhzp6FrIDEKyyZCqrgGKVPSTuUTNVyF8kubJ1MTcnLuazbKy9zw=='),
        ),
    ]
