# Generated by Django 5.1.1 on 2024-10-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrifto', '0003_device_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_fa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
