# Generated by Django 5.1.1 on 2024-10-02 21:01

import thrifto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrifto', '0004_userprofile_two_fa_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='file_upload',
            field=models.FileField(blank=True, help_text='Upload a JPG, PNG, or PDF file. Max size: 10MB.', null=True, upload_to='uploads/', validators=[thrifto.models.validate_file_type, thrifto.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='confirm_kyc_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='confirm_kyc_phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kyc_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kyc_phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
