# Generated by Django 5.1.1 on 2024-10-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thrifto', '0006_alter_userprofile_email_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='owner',
            new_name='admin',
        ),
    ]
