# Generated by Django 5.1.2 on 2024-10-22 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='periods_covered',
            field=models.ManyToManyField(related_name='contributions', to='Notifications.contributionperiod'),
        ),
        migrations.AddField(
            model_name='contributionreminder',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notifications.contributionperiod'),
        ),
        migrations.AddField(
            model_name='contributionreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributionreminder',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notifications.group'),
        ),
        migrations.AddField(
            model_name='contributionperiod',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_periods', to='Notifications.group'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notifications.group'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contributionperiod',
            unique_together={('group', 'period_number')},
        ),
    ]
