# Generated by Django 5.1.2 on 2024-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('SIGNUP', 'Sign Up'), ('LOGIN', 'Login'), ('KYC_CONFIRMED', 'KYC Confirmed'), ('FORGET_PASSWORD', 'Forget_password'), ('PAYMENT_SUCCESSFUL', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('CONTRIBUTION_SUCCESSFUL', 'Contribution Successful'), ('CYCLE_PAYMENT_RECEIVED', 'Cycle Payment Received'), ('FAILED_PAYMENT', 'Failed Payment'), ('WALLET_WITHDRAWAL', 'Wallet Withdrawal Successful'), ('WALLET_DEPOSIT', 'Wallet Deposit Successful'), ('GROUP_JOIN', 'Group Join Successful'), ('GROUP_REMOVAL', 'Group Removal Alert'), ('GROUP_INVITATION', 'Group Invitation Received')], max_length=25),
        ),
    ]
